### ISSUE TITLE
Add option to run for specified number of cycles 

### ISSUE THREAD

**Issue by N5RWK** [Guenael/rtlsdr-wsprd#11]
Thanks for a very useful program.  My Pi 3/RTL-SDR is running very nicely, listening on 20m and reporting up to wsprnet.org.

I was wondering if you could add an option to run rtlsdr-wsprd for a specified number of 2-minute receive cycles, then have the program exit.  For example, if the option was "-t 30", rtlsdr-wsprd would listen for a total of 60 minutes and exit.  

This would allow me to create a shell script with a series of rtlsdr-wsprd commands listening at different frequencies.

Roger N5RWK

**Comment by Guenael** [comment]
Hello Roger,
There is other ways to stop a service with Linux (using crontab for example), but why not, and this is a minor update. I will check to write a patch this week-end.
Good day,

**Comment by ve2vax** [comment]
Hi , you can also , run it with a script , that will span many band . or  put a sleep and run again . 
see in ve2vax git ://
rtlsdr-wsprd/auto-wspr.sh

73

**Comment by N5RWK** [comment]
Guenael,

Thanks, I appreciate it!  My C programming skills are rather suspect at best :-)  I looked at ve2vax's script, he did a nice job with it.  But seems a touch more elegant to do it from within the program.

73
Roger N5RWK

**Comment by Guenael** [comment]
Done. Use "-n 9" for 8 full iterations (the last one will be truncated due to the threading)
73

**Comment by N5RWK** [comment]
Guénael,  thanks very much!  
Roger N5RWK
