### ISSUE TITLE
rtl-sdr wsprd is more sensitive on RPi3 than RPi2

### ISSUE THREAD

**Issue by Claudio-Sjo** [Guenael/rtlsdr-wsprd#133]
Hi,
thank you for this nice project.
Apart for setting udev, the instructions are very useful and I managed to test it on RPI zero W, RPI2 and RPi3.
I noticed that the same rtl-sdr V3 decodes many more signals on RPi3 than on the other two.
I actually didn't manage to undestand why, I noticed that on the zero the CPU goes from 14% when capturing data to 98% when decoding, whereas on RPi3 is much lower.
Having had a look at the source code, I didn't find any issue, still what should run identically actually doesn't.

Is there anything I can do for helping?

73 de Claudio SA0PRF

**Comment by Guenael** [comment]
You can check if the capture starts at the right time, and don't miss the beginning.
About the CPU load, Raspberry Pi Zero W (BCM2835) is a single-core processor.
The capture uses a thread, and the decoding uses another one. Works perfectly on a RPi3, but with only one core, it could be an issue if the capture thread cannot get enough cycles. The decoding part should run with a low priority, but I never tested it on a RPi0

**Comment by Claudio-Sjo** [comment]
I see, RPi2 is even slower than Pi Zero W.
Then it may be good to add a note on the project about what I've seen, so that people knows.
I am doing some hacking on your code for FT8, if you wish you can join at https://github.com/Claudio-Sjo/rtlsdr-ft8d
Mainly I plan to add a ncurses GUI and a BS170 + LPF for transmission so that it would be possible having FT8 full traffic.
The PSK reported code I am not sure actually.
