### ISSUE TITLE
Cannot run on Pizero W - update Makefile

### ISSUE THREAD

**Issue by Claudio-Sjo** [Guenael/rtlsdr-wsprd#142]
Change compilation flag in Makefile for RPi zero. New Makefile:

```
CC = clang
CFLAGS = -O3 -std=gnu17
LIBS = -lusb-1.0 -lrtlsdr -lpthread -lfftw3f -lcurl -lm

ifeq ($(findstring armv6,$(shell uname -m)),armv6)
PI_VERSION = -DRPI1 --target=arm-linux-gnueabihf -mcpu=arm1176jzf-s -mfloat-abi=hard
else
PI_VERSION = -DRPI23
endif

OBJS = rtlsdr_wsprd.o wsprd/wsprd.o wsprd/wsprsim_utils.o wsprd/wsprd_utils.o wsprd/tab.o wsprd/fano.o wsprd/nhash.o

TARGETS = rtlsdr_wsprd

.PHONY: all clean

all: $(TARGETS)

%.o: %.c
        ${CC} ${CFLAGS} $(PI_VERSION) -c $< -o $@

rtlsdr_wsprd: $(OBJS)
        $(CC) -o $@ $^ $(LIBS)

clean:
        rm -f *.o wsprd/*.o $(TARGETS) fftw_wisdom.dat hashtable.txt selftest.iq

install:
        install rtlsdr_wsprd /usr/local/bin/rtlsdr_wsprd
```

**Comment by Guenael** [comment]
Could you please provide a Makefile that works also for other architectures? (you're focusing only on Arm devices with this Makefile)

**Comment by Guenael** [comment]
I made this update, please let me know if it works for you.
https://github.com/Guenael/rtlsdr-wsprd/blob/main/Makefile#L9-L22

**Comment by Claudio-Sjo** [comment]
It doesn't work.
The problem is clang compiling for the wrong architecture, you need to specify
--target=arm-linux-gnueabihf -mcpu=arm1176jzf-s -mfloat-abi=hard

73 de SA0PRF

**Comment by Guenael** [comment]
Update completed : https://github.com/Guenael/rtlsdr-wsprd/blob/main/Makefile#L12
