### ISSUE TITLE
First cycle is not decoded

### ISSUE THREAD

**Issue by rsnow** [Guenael/rtlsdr-wsprd#19]
postSpots() is not reached on first iteration, it may be wsprDecoder() that isn't getting called, but I am not certain.  I wonder if this is related to the sig11's from subtraction method?

**Comment by Guenael** [comment]
-- Sorry for the (extra-long) delay, I just recovered my access to GitHub, and I was off radio activities --

Hi @rsnow ,

wsprDecoder should be called at all the time, not sure to understand your point.
If you have some logs, additional info / sequential screenshots, I can try to investigate.

73
