### ISSUE TITLE
Supporting rx_tools / getting samples from stdin

### ISSUE THREAD

**Issue by marcotrevisan** [Guenael/rtlsdr-wsprd#20]
Hi Guenael,

I'm using rtlsdr-wsprd on Raspberry Pi 3. I'd like to use my SDRplay RSP2 Pro to take advantage of its much better RX performance. 
At first, I was about to ask if it's possible to add support for rx_tools to enable more hardware, but then I considered what this tool is really focused on: WSPR reporting from a IQ data stream.

Hence the second and perhaps more useful question: why not supporting stdin input (so the command line would look like 'rx_sdr [options] | rtlsdr_wsprd -'), like i.e. the OpenWebRX's "csdr" tool?
That would improve separation of concerns and the tool would be usable in a lot more scenarios.

I've searched the web but did not find a plain implementation that reads from stdin, your implementation was the closest I was able to find.

Thanks in advance, kind regards.
  IU3JSX Marco

**Comment by Guenael** [comment]
-- Sorry for the (extra-long) delay, I just recovered my access to GitHub, and I was off radio activities --

Hi @marcotrevisan ,

This project is very focused on RTL devices, and I will not extend the device compatibility of this project.
I created an other project for Airspy devices for example, and for sure, it's possible to adapt wsprd to SDRplay.
But it's not in my plan, and I don't own this device. If you have some dev skill, it should be easy, if I can do it, you can do it too! :)

73,
