### ISSUE TITLE
Support for PTT control line

### ISSUE THREAD

**Issue by lu7did** [Guenael/rtlsdr-wsprd#21]
Hi,

If integrated with a WSPR beacon to form a transceiver a control line acting as a PTT is needed, it is required to turn own an amplifier but, more important, to switch the antenna from the rtl-sdr device and whatever it's being used for transmission (even the raspberry pi itself with programs such as WsprryPi or others).

Thanks in advance, Pedro LU7DID

**Comment by Guenael** [comment]
Hi @lu7did ,

Technically, yep it should be easy to allocate a pin of the raspberry pi, and use it to drive a fet+relay.
I will not do this for this project right now, but I will do it for a next project, a FT8 transceiver based on RPi.
At some point, I will retro-fit this feature to rtlsdr-wsprd.

Thanks, 73,
