### ISSUE TITLE
Running error on openwrt

### ISSUE THREAD

**Issue by d9394** [Guenael/rtlsdr-wsprd#23]
![tmp20191018140437](https://user-images.githubusercontent.com/15172911/67069729-97831880-f1b0-11e9-9a8b-b14a6ae6714b.jpg)
 I have successed compile rtlsdr_wsprd from source on the openwrt(version 18.06.02) and cpu hardware is mt7621 chipset,  when I run it appear a error

**Comment by d9394** [comment]
![tmp20191018145256](https://user-images.githubusercontent.com/15172911/67072445-770a8c80-f1b7-11e9-9f97-197e019acdb8.jpg)
after add some checkpoint

**Comment by d9394** [comment]
[putty.log](https://github.com/Guenael/rtlsdr-wsprd/files/3744939/putty.log)
 log file with command: strace -tt rdlsdr_wsprd

**Comment by Guenael** [comment]
-- Sorry for the (extra-long) delay, I just recovered my access to GitHub, and I was off radio activities --

Hi @d9394 ,

Well, the end of the log didn't help too much... 
```
00:49:55.977082 nanosleep({tv_sec=0, tv_nsec=250000000}, RX done! [Buffer size: 43500]
Search & decode the signal
 <unfinished ...>) = ?
00:49:56.035480 +++ killed by SIGSEGV +++
Segmentation fault
]0;root@OpenWrt: ~root@OpenWrt:~# 
```

Did you try with a similar project based on files only ?
Ex. https://github.com/k9an/old_wsprcan

It could be also an allocation issue. This MR (merged) could fix an issue related to this, but this one is pretty rare.
https://github.com/Guenael/rtlsdr-wsprd/pull/22

73
