### ISSUE TITLE
callsign with 9 characters in length

### ISSUE THREAD

**Issue by alexandrealvesneto** [Guenael/rtlsdr-wsprd#25]
When I use a call sign with 9 characters in length
the Spot show a different call sign.

Example: I have a Tx transmitting via PU2790SWL call sign but rtlsdr-wsprd is reporting a
different call sign --> PU1QSK

Starting rtlsdr-wsprd (2020-09-09, 00:57z) -- Version 0.2
  Callsign     : PU2790SWL
  Locator      : GG66NL
  Dial freq.   : 21094600 Hz
  Real freq.   : 21094600 Hz
  PPM factor   : 0
  Auto gain    : enable
Wait for time sync (start in 32 sec)

Spot : -6.65 -0.57  21.096013 -4  PU1QSK GG66 10
Spot : -7.54 -0.81  21.096133 -4  PU1QSK GG66 10

**Comment by Guenael** [comment]
-- Sorry for the (extra-long) delay, I just recovered my access to GitHub, and I was off radio activities --

Hi @alexandrealvesneto,
I guess the pattern is the same with genuine versions of the WSPR decoder. The algo is designed to fit regular callsigns in a specific optimized format, and long format are not working properly (there is some documentation an the WSPR protocol).

You can double-check with this project : 
https://github.com/k9an/old_wsprcan

73
