### ISSUE TITLE
Feature request - run script

### ISSUE THREAD

**Issue by mkarliner** [Guenael/rtlsdr-wsprd#67]
I'd like to run something like https://github.com/JamesP6000/WsprryPi
in tandem with  rtlsdr-wsprd. 

To do this, I'd like an option to run a script at defined intervals, so I
can trigger a T/R relay and run WsprryPi in single shot mode.

This would make an absolutely tiny full WSPR station.

**Comment by Guenael** [comment]
Think you can do this easily, with this option:
```
-n max iterations (default: 0 = infinite loop)
```

If you set this option to one, and if your script wait one rtlsdr-wsprd to exit, then you can switch & TX. It could work.

I noticed rtlsdr-wsprd is reluctant to quit properly... Another bug related to my management with pthread. Not an easy one.

**Comment by sm3ulc** [comment]
Great!
