### ISSUE TITLE
Doesn't not exit on control C

### ISSUE THREAD

**Issue by mkarliner** [Guenael/rtlsdr-wsprd#68]
Catching a signal sets the rx_state.exit_flag, but  does not result in the program terminating.

**Comment by Guenael** [comment]
Yep, I was on it... I guess the thread local variables are not sync with the parent. Or something like that.

**Comment by Guenael** [comment]
Works fine on an x86_64, but not on a Raspberry Pi.
@mkarliner Did you experience this issue on an RPi?

**Comment by Guenael** [comment]
Related to the PiOS image used, and possibly to some pthread issue.
Works fine on Linux x86_64, and an old version of Raspbian.
I will update the README file.
