### ISSUE TITLE
Direct Sampling Mode hard coded to 1

### ISSUE THREAD

**Issue by mkarliner** [Guenael/rtlsdr-wsprd#94]
rtl_result = rtlsdr_set_direct_sampling(rtl_device, 1);

**Comment by mkarliner** [comment]
However, when changed to 2...
![image](https://user-images.githubusercontent.com/1651042/146371942-348d9970-7be5-4014-a8ad-2db136fdf2e2.png)

**Comment by IZ7BOJ** [comment]
You’re right, I always used 2 !
It seems that in this last version it’s not possible to pass 0/1/2 as integer parameter

**Comment by Guenael** [comment]
Hi, you're right!
I will rollback this direct-sampling option.

**Comment by Guenael** [comment]
I fixed the direct sampling option:
https://github.com/Guenael/rtlsdr-wsprd/pull/97

And made a new release to include this fix:
https://github.com/Guenael/rtlsdr-wsprd/releases/tag/0.4.1

Hope this helps.
